def update_fds(self):
    try:
        self.fd_nums.update(self.process.num_fds())
    except Exception as e:
        Log.error(traceback.format_exc(e))
